"""Parse hierarchical UVM table-printer output into RM parameter assignments."""

from __future__ import print_function

import argparse
import ast
import importlib.util
import json
import keyword
import os
import re
import sys
import tempfile
from collections import OrderedDict


GENERATED_HEADER = "# Auto-generated by utils/parse_uvm_table_print.py"
JSON_FORMAT = "uvm_table_printer/v1"


class UvmTableParserError(Exception):
    """Raised when parser input or output configuration is invalid."""


class DetailedArgumentParser(argparse.ArgumentParser):
    """Argument parser that shows complete guidance before CLI errors."""

    def error(self, message):
        self.print_help(sys.stderr)
        self.exit(2, "\nerror: {0}\n".format(message))


def convert_value(raw_value):
    """Convert a supported UVM table value into a Python value."""
    value = raw_value.strip()

    if re.match(r"^[+-]?[0-9]+$", value):
        return int(value, 10)

    if re.match(r"^[+-]?0[xX][0-9a-fA-F_]+$", value):
        return int(value.replace("_", ""), 16)

    if re.match(r"^[+-]?0[bB][01_]+$", value):
        return int(value.replace("_", ""), 2)

    if re.match(r"^[+-]?0[oO][0-7_]+$", value):
        return int(value.replace("_", ""), 8)

    sv_match = re.match(
        r"^(?P<sign>[+-]?)(?P<size>[0-9]+)?'(?P<signed>[sS])?"
        r"(?P<base>[bBoOdDhH])(?P<digits>[0-9a-fA-F_]+)$",
        value,
    )
    if sv_match:
        base = {
            "b": 2,
            "o": 8,
            "d": 10,
            "h": 16,
        }[sv_match.group("base").lower()]
        converted = int(sv_match.group("digits").replace("_", ""), base)
        size_text = sv_match.group("size")
        if sv_match.group("signed") and size_text:
            size = int(size_text, 10)
            sign_bit = 1 << (size - 1)
            if converted & sign_bit:
                converted -= 1 << size
        if sv_match.group("sign") == "-":
            converted = -converted
        return converted

    if len(value) >= 2 and value[0] in ("'", '"') and value[-1] == value[0]:
        try:
            literal = ast.literal_eval(value)
        except (SyntaxError, ValueError):
            return value
        if isinstance(literal, str):
            return literal

    return value


def _header_columns(line):
    stripped = line.strip()
    if not re.match(r"^Name\s+Type\s+Size\s+Value$", stripped):
        return None
    return (
        line.index("Type"),
        line.index("Size"),
        line.index("Value"),
    )


def _parse_row(line, columns):
    if columns is not None and len(line) > columns[0]:
        type_column, size_column, value_column = columns
        name_field = line[:type_column].rstrip()
        name = name_field.strip()
        field_type = line[type_column:size_column].strip()
        size = line[size_column:value_column].strip()
        value = line[value_column:].strip()
        if (
            re.match(r"^\S+$", name or "")
            and field_type
            and re.match(r"^(?:-|[0-9]+)$", size)
        ):
            indent = len(name_field) - len(name_field.lstrip())
            return indent, name, field_type, size, value

    match = re.match(
        r"^(?P<indent>\s*)(?P<name>\S+)\s{2,}"
        r"(?P<type>\S.*?)\s{2,}(?P<size>\S+)\s{2,}(?P<value>.*?)\s*$",
        line,
    )
    if not match:
        return None
    if not re.match(r"^(?:-|[0-9]+)$", match.group("size")):
        return None
    return (
        len(match.group("indent")),
        match.group("name"),
        match.group("type"),
        match.group("size"),
        match.group("value"),
    )


def _is_unsupported_value(value):
    return not value or value == "-" or value.startswith("@")


def _iter_table_rows(text):
    columns = None

    for line in text.splitlines():
        detected_columns = _header_columns(line)
        if detected_columns is not None:
            columns = detected_columns
            yield None
            continue

        stripped = line.strip()
        if not stripped or set(stripped) <= set("-="):
            continue

        row = _parse_row(line, columns)
        if row is not None:
            yield row


def parse_uvm_table_text(text):
    """Return ``(hierarchical_path, value)`` pairs in table order."""
    parsed_items = []
    hierarchy = []

    for row in _iter_table_rows(text):
        if row is None:
            hierarchy = []
            continue

        indent, name, _field_type, _size, raw_value = row
        while hierarchy and hierarchy[-1][0] >= indent:
            hierarchy.pop()
        path_parts = [item[1] for item in hierarchy] + [name]
        hierarchy.append((indent, name))

        if _is_unsupported_value(raw_value):
            continue
        parsed_items.append((".".join(path_parts), convert_value(raw_value)))

    return parsed_items


def _parse_size(raw_size):
    if raw_size == "-":
        return None
    return int(raw_size, 10)


def _new_tree_node(name, field_type, raw_size, raw_value):
    return {
        "name": name,
        "type": field_type,
        "size": _parse_size(raw_size),
        "_raw_value": raw_value,
        "_is_reference": raw_value.startswith("@"),
        "_children": [],
    }


def _finalize_tree_node(node):
    result = OrderedDict()
    result["name"] = node["name"]
    result["type"] = node["type"]
    result["size"] = node["size"]

    children = node["_children"]
    if node["_is_reference"] or children:
        result["children"] = [_finalize_tree_node(child) for child in children]
    else:
        result["value"] = convert_value(node["_raw_value"])
    return result


def parse_uvm_table_tree(text):
    """Return hierarchical UVM table nodes in source order."""
    roots = []
    hierarchy = []

    for row in _iter_table_rows(text):
        if row is None:
            hierarchy = []
            continue

        indent, name, field_type, raw_size, raw_value = row
        node = _new_tree_node(name, field_type, raw_size, raw_value)

        while hierarchy and hierarchy[-1][0] >= indent:
            hierarchy.pop()
        if hierarchy:
            hierarchy[-1][1]["_children"].append(node)
        else:
            roots.append(node)
        hierarchy.append((indent, node))

    return [_finalize_tree_node(root) for root in roots]


def render_uvm_table_json(roots):
    """Render deterministic versioned JSON with one final newline."""
    document = OrderedDict()
    document["format"] = JSON_FORMAT
    document["roots"] = roots
    return json.dumps(document, indent=2, ensure_ascii=True) + "\n"


def _mapping_candidates(path):
    parts = path.split(".")
    candidates = [path]
    if len(parts) > 1:
        candidates.append(".".join(parts[1:]))
    if parts[-1] not in candidates:
        candidates.append(parts[-1])
    return candidates


def _validate_parameter_name(name):
    if not isinstance(name, str) or not name.isidentifier() or keyword.iskeyword(name):
        raise UvmTableParserError(
            "invalid RM parameter name {!r}: expected a Python identifier".format(name)
        )


def apply_mapping(parsed_items, name_map, keep_unmapped=True):
    """Map hierarchical UVM names to unique flat RM parameter names."""
    if not isinstance(name_map, dict):
        raise UvmTableParserError("invalid mapping: PARAM_NAME_MAP must be a dict")

    mapped_items = []
    seen_names = set()
    for path, value in parsed_items:
        rm_name = None
        for candidate in _mapping_candidates(path):
            if candidate in name_map:
                rm_name = name_map[candidate]
                break

        if rm_name is None:
            if not keep_unmapped:
                continue
            rm_name = path.rsplit(".", 1)[-1]

        _validate_parameter_name(rm_name)
        if rm_name in seen_names:
            raise UvmTableParserError(
                "duplicate RM parameter name {!r} produced from {!r}".format(
                    rm_name, path
                )
            )
        seen_names.add(rm_name)
        mapped_items.append((rm_name, value))

    return mapped_items


def render_python_para_get(mapped_items):
    """Render deterministic Python source containing ``para_get``."""
    lines = [GENERATED_HEADER, "", "def para_get(parse):"]
    item_count = 0
    seen_names = set()

    for name, value in mapped_items:
        _validate_parameter_name(name)
        if name in seen_names:
            raise UvmTableParserError(
                "duplicate RM parameter name {!r} while rendering".format(name)
            )
        seen_names.add(name)
        lines.append("    parse.{0} = {1}".format(name, repr(value)))
        item_count += 1

    if item_count == 0:
        lines.append("    pass")
    return "\n".join(lines) + "\n"


def load_mapping_file(path):
    """Load ``PARAM_NAME_MAP`` and optional ``KEEP_UNMAPPED`` from a file."""
    if not os.path.isfile(path):
        raise UvmTableParserError("mapping file not found: {0}".format(path))

    try:
        spec = importlib.util.spec_from_file_location("uvm_table_parameter_mapping", path)
        if spec is None or spec.loader is None:
            raise UvmTableParserError("invalid mapping file: cannot load module")
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
    except UvmTableParserError:
        raise
    except Exception as exc:
        raise UvmTableParserError("invalid mapping file: {0}".format(exc))

    if not hasattr(module, "PARAM_NAME_MAP"):
        raise UvmTableParserError(
            "invalid mapping file: PARAM_NAME_MAP missing"
        )
    name_map = module.PARAM_NAME_MAP
    if not isinstance(name_map, dict):
        raise UvmTableParserError(
            "invalid mapping file: PARAM_NAME_MAP must be a dict"
        )

    keep_unmapped = getattr(module, "KEEP_UNMAPPED", True)
    if not isinstance(keep_unmapped, bool):
        raise UvmTableParserError(
            "invalid mapping file: KEEP_UNMAPPED must be a bool"
        )
    return name_map, keep_unmapped


def _read_text_file(path, label):
    if not os.path.isfile(path):
        raise UvmTableParserError("{0} file not found: {1}".format(label, path))
    try:
        with open(path, "r", encoding="utf-8") as handle:
            return handle.read()
    except (IOError, OSError) as exc:
        raise UvmTableParserError(
            "cannot read {0} file {1}: {2}".format(label, path, exc)
        )


def _write_output_file(path, content):
    output_path = os.path.abspath(path)
    output_directory = os.path.dirname(output_path)
    if not os.path.isdir(output_directory):
        raise UvmTableParserError(
            "cannot parse output path: directory does not exist: {0}".format(
                output_directory
            )
        )
    if os.path.isdir(output_path):
        raise UvmTableParserError(
            "cannot parse output path: path is a directory: {0}".format(path)
        )

    temporary_path = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            newline="\n",
            dir=output_directory,
            prefix=".uvm_table_",
            suffix=".tmp",
            delete=False,
        ) as handle:
            temporary_path = handle.name
            handle.write(content)
        os.replace(temporary_path, output_path)
    except (IOError, OSError) as exc:
        if temporary_path is not None and os.path.exists(temporary_path):
            try:
                os.remove(temporary_path)
            except (IOError, OSError):
                pass
        raise UvmTableParserError(
            "cannot write output file {0}: {1}".format(path, exc)
        )


def build_argument_parser():
    parser = DetailedArgumentParser(
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description=(
            "Parse hierarchical uvm_table_printer text and generate Python "
            "para_get or JSON output."
        ),
        epilog=(
            "examples:\n"
            "  Python output (default):\n"
            "    python utils/parse_uvm_table_print.py `\n"
            "      --input input.txt `\n"
            "      --mapping mapping.py `\n"
            "      --output generated_para.py\n"
            "\n"
            "  Hierarchical JSON output:\n"
            "    python utils/parse_uvm_table_print.py `\n"
            "      --input input.txt `\n"
            "      --format json `\n"
            "      --output generated_table.json\n"
            "\n"
            "notes:\n"
            "  --input and --output are required.\n"
            "  --format defaults to python.\n"
            "  --mapping and --unmapped apply only to Python output.\n"
            "  Run with --help to display this guide."
        ),
    )
    parser.add_argument(
        "--input",
        required=True,
        metavar="PATH",
        help="input UVM table-printer text file",
    )
    parser.add_argument(
        "--format",
        choices=("python", "json"),
        default="python",
        help="output format; python preserves the existing para_get flow",
    )
    parser.add_argument(
        "--mapping",
        metavar="PATH",
        help="optional Python name-mapping file; invalid for JSON output",
    )
    parser.add_argument(
        "--output",
        required=True,
        metavar="PATH",
        help="generated .py or .json output file",
    )
    parser.add_argument(
        "--unmapped",
        choices=("keep", "ignore"),
        help="Python output policy for names absent from the mapping",
    )
    return parser


def main(argv=None):
    parser = build_argument_parser()
    args = parser.parse_args(argv)

    try:
        text = _read_text_file(args.input, "input")
        if args.format == "json":
            if args.mapping or args.unmapped is not None:
                raise UvmTableParserError(
                    "--mapping and --unmapped are only valid with --format python"
                )
            roots = parse_uvm_table_tree(text)
            if not roots:
                raise UvmTableParserError(
                    "no supported table nodes found in input file: {0}".format(
                        args.input
                    )
                )
            rendered = render_uvm_table_json(roots)
        else:
            parsed_items = parse_uvm_table_text(text)
            if not parsed_items:
                raise UvmTableParserError(
                    "no supported parameter rows found in input file: {0}".format(
                        args.input
                    )
                )

            name_map = {}
            keep_unmapped = True
            if args.mapping:
                name_map, keep_unmapped = load_mapping_file(args.mapping)
            if args.unmapped is not None:
                keep_unmapped = args.unmapped == "keep"

            mapped_items = apply_mapping(parsed_items, name_map, keep_unmapped)
            rendered = render_python_para_get(mapped_items)
        _write_output_file(args.output, rendered)
    except UvmTableParserError as exc:
        print("error: {0}".format(exc), file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
