"""Compile UVM table-printer JSON into an RM schema dictionary."""

from __future__ import print_function

import argparse
import json
import os
import re
import sys
import tempfile
from collections import OrderedDict

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if REPO_ROOT not in sys.path:
    sys.path.insert(0, REPO_ROOT)

from utils.parse_uvm_table_print import parse_uvm_table_tree


GENERATED_HEADER = "Generated by utils/uvm_table_schema_adapter.py"
DEFAULT_WORD_WIDTH = 32


class UvmTableSchemaAdapterError(Exception):
    """Raised when UVM table schema compilation cannot continue."""


class CompileResult(object):
    def __init__(self, schema_dict, report):
        self.schema_dict = schema_dict
        self.report = report


def _ordered_dict():
    return OrderedDict()


def _parse_bit_range(field_type):
    match = re.search(r"\[(?P<msb>[0-9]+):(?P<lsb>[0-9]+)\]", field_type or "")
    if not match:
        return None
    msb = int(match.group("msb"), 10)
    lsb = int(match.group("lsb"), 10)
    if msb < lsb:
        raise UvmTableSchemaAdapterError(
            "invalid bit range in type {0!r}".format(field_type)
        )
    return msb, lsb


def _is_word_marker(name):
    return re.match(r"^word[0-9]+$", name or "") is not None


def _word_index(name):
    return int(name[4:], 10)


def _is_reserved(name):
    compact = re.sub(r"[^A-Za-z0-9]", "", name or "").lower()
    return compact.startswith("rsv") or compact.startswith("reserved")


def _is_payload_node(node):
    name = (node.get("name") or "").lower()
    field_type = (node.get("type") or "").lower()
    return name == "payload" or field_type.startswith("da(")


def _path_for_name(ancestors):
    parts = []
    for item in ancestors[1:]:
        name = item.get("name")
        if not name:
            continue
        if name.endswith("_param"):
            continue
        parts.append(name)
    return parts


def _schema_field_name(scope, ancestors, raw_name, word, msb, lsb):
    parts = [scope]
    parts.extend(_path_for_name(ancestors))
    parts.append("{0}__w{1}_b{2}_{3}".format(raw_name, word, msb, lsb))
    return ".".join(parts)


def _field_from_node(scope, ancestors, node, current_word):
    if current_word is None:
        raise UvmTableSchemaAdapterError(
            "field {0!r} appears before a word marker".format(node.get("name"))
        )
    bit_range = _parse_bit_range(node.get("type"))
    if bit_range is None:
        raise UvmTableSchemaAdapterError(
            "field {0!r} type {1!r} is missing [msb:lsb]".format(
                node.get("name"), node.get("type")
            )
        )
    msb, lsb = bit_range
    width = node.get("size")
    expected_width = msb - lsb + 1
    if width != expected_width:
        raise UvmTableSchemaAdapterError(
            "field {0!r} size {1!r} does not match bit range width {2}".format(
                node.get("name"), width, expected_width
            )
        )

    raw_name = node["name"]
    field = _ordered_dict()
    field["name"] = _schema_field_name(
        scope,
        ancestors,
        raw_name,
        current_word,
        msb,
        lsb,
    )
    field["original_name"] = raw_name
    field["scope"] = scope
    field["word"] = current_word
    field["msb"] = msb
    field["lsb"] = lsb
    field["width"] = width
    field["reserved"] = _is_reserved(raw_name)
    return field


def _report_payload(node, scope, current_word, report):
    payload = _ordered_dict()
    payload["scope"] = scope
    payload["name"] = node.get("name")
    payload["word"] = current_word
    payload["type"] = node.get("type")
    payload["reason"] = "runtime_payload"
    report["payload_ranges"].append(payload)
    report["payload_range_count"] += 1
    report["skipped_field_count"] += 1


def _walk_nodes(nodes, scope, ancestors, state, fields, report):
    current_word = state.get("current_word")
    for node in nodes:
        name = node.get("name")
        children = node.get("children")
        if children is not None:
            child_state = {"current_word": current_word}
            _walk_nodes(
                children,
                scope,
                ancestors + [node],
                child_state,
                fields,
                report,
            )
            current_word = child_state.get("current_word")
            state["current_word"] = current_word
            continue

        if _is_word_marker(name):
            current_word = _word_index(name)
            state["current_word"] = current_word
            continue

        if _is_payload_node(node):
            _report_payload(node, scope, current_word, report)
            continue

        field = _field_from_node(scope, ancestors, node, current_word)
        fields.append(field)
        report["field_count"] += 1
        if field["reserved"]:
            report["reserved_count"] += 1
        raw_name = field["original_name"]
        report["_raw_name_counts"][raw_name] = (
            report["_raw_name_counts"].get(raw_name, 0) + 1
        )


def _new_report(schema_id, word_width):
    report = _ordered_dict()
    report["schema_id"] = schema_id
    report["word_width"] = word_width
    report["word_count"] = 0
    report["field_count"] = 0
    report["reserved_count"] = 0
    report["duplicate_raw_name_count"] = 0
    report["payload_range_count"] = 0
    report["skipped_field_count"] = 0
    report["warnings"] = []
    report["payload_ranges"] = []
    report["_raw_name_counts"] = {}
    return report


def _finalize_report(report, fields):
    max_word = -1
    for field in fields:
        if field["word"] > max_word:
            max_word = field["word"]
    for payload in report["payload_ranges"]:
        word = payload.get("word")
        if word is not None and word > max_word:
            max_word = word
    report["word_count"] = max_word + 1 if max_word >= 0 else 0
    report["duplicate_raw_name_count"] = sum(
        1 for count in report["_raw_name_counts"].values() if count > 1
    )
    del report["_raw_name_counts"]
    return report


def _as_roots(document_or_roots):
    if isinstance(document_or_roots, dict):
        if "roots" not in document_or_roots:
            raise UvmTableSchemaAdapterError(
                "UVM table JSON document must contain roots"
            )
        return document_or_roots["roots"]
    return document_or_roots


def compile_schema_from_uvm_table_json(
    document_or_roots,
    schema_id,
    scope_rules,
    word_width=DEFAULT_WORD_WIDTH,
):
    if not isinstance(scope_rules, dict) or not scope_rules:
        raise UvmTableSchemaAdapterError("scope_rules must be a non-empty dict")
    roots = _as_roots(document_or_roots)
    if not isinstance(roots, list) or not roots:
        raise UvmTableSchemaAdapterError("UVM table roots must be a non-empty list")

    fields = []
    report = _new_report(schema_id, word_width)
    for root in roots:
        root_name = root.get("name")
        if root_name not in scope_rules:
            raise UvmTableSchemaAdapterError(
                "no scope rule for source table {0!r}".format(root_name)
            )
        scope = scope_rules[root_name]
        if scope not in ("global", "packet", "cell"):
            raise UvmTableSchemaAdapterError(
                "invalid scope {0!r} for source table {1!r}".format(
                    scope, root_name
                )
            )
        children = root.get("children")
        if children is None:
            raise UvmTableSchemaAdapterError(
                "source table {0!r} must be a container".format(root_name)
            )
        _walk_nodes(children, scope, [root], {}, fields, report)

    _finalize_report(report, fields)
    schema = _ordered_dict()
    schema["schema_id"] = schema_id
    schema["word_width"] = word_width
    schema["word_count"] = report["word_count"]
    metadata = _ordered_dict()
    metadata["source_format"] = "uvm_table_printer/v1"
    metadata["generated_by"] = GENERATED_HEADER
    metadata["scope_rules"] = OrderedDict(sorted(scope_rules.items()))
    metadata["payload_ranges"] = report["payload_ranges"]
    schema["metadata"] = metadata
    schema["fields"] = fields
    return CompileResult(schema, report)


def render_json(data):
    return json.dumps(data, indent=2, ensure_ascii=True) + "\n"


def _read_text(path):
    if not os.path.isfile(path):
        raise UvmTableSchemaAdapterError("input file not found: {0}".format(path))
    try:
        with open(path, "r", encoding="utf-8") as handle:
            return handle.read()
    except (IOError, OSError) as exc:
        raise UvmTableSchemaAdapterError(
            "cannot read input file {0}: {1}".format(path, exc)
        )


def _read_json(path):
    if not os.path.isfile(path):
        raise UvmTableSchemaAdapterError("input file not found: {0}".format(path))
    try:
        with open(path, "r", encoding="utf-8") as handle:
            return json.load(handle)
    except (IOError, OSError, ValueError) as exc:
        raise UvmTableSchemaAdapterError(
            "cannot read JSON input file {0}: {1}".format(path, exc)
        )


def _write_file(path, content):
    output_path = os.path.abspath(path)
    output_directory = os.path.dirname(output_path)
    if not os.path.isdir(output_directory):
        raise UvmTableSchemaAdapterError(
            "output directory does not exist: {0}".format(output_directory)
        )
    temporary_path = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            newline="\n",
            dir=output_directory,
            prefix=".uvm_schema_",
            suffix=".tmp",
            delete=False,
        ) as handle:
            temporary_path = handle.name
            handle.write(content)
        os.replace(temporary_path, output_path)
    except (IOError, OSError) as exc:
        if temporary_path is not None and os.path.exists(temporary_path):
            try:
                os.remove(temporary_path)
            except (IOError, OSError):
                pass
        raise UvmTableSchemaAdapterError(
            "cannot write output file {0}: {1}".format(path, exc)
        )


def _parse_scope_rule(text):
    if "=" not in text:
        raise UvmTableSchemaAdapterError(
            "scope rule must use TABLE=SCOPE syntax: {0!r}".format(text)
        )
    table, scope = text.split("=", 1)
    table = table.strip()
    scope = scope.strip()
    if not table or not scope:
        raise UvmTableSchemaAdapterError(
            "scope rule must use TABLE=SCOPE syntax: {0!r}".format(text)
        )
    return table, scope


def _load_scope_rules(scope_rule_values):
    rules = OrderedDict()
    for value in scope_rule_values or []:
        table, scope = _parse_scope_rule(value)
        rules[table] = scope
    return rules


def build_argument_parser():
    parser = argparse.ArgumentParser(
        description=(
            "Compile existing UVM table-printer parsed JSON into an RM schema "
            "dictionary."
        )
    )
    input_group = parser.add_mutually_exclusive_group(required=True)
    input_group.add_argument(
        "--input",
        metavar="PATH",
        help="UVM table-printer text input; parsed with the existing parser",
    )
    input_group.add_argument(
        "--json-input",
        metavar="PATH",
        help="pre-rendered uvm_table_printer/v1 JSON input",
    )
    parser.add_argument("--schema-id", required=True, help="output schema_id")
    parser.add_argument(
        "--scope-rule",
        action="append",
        default=[],
        metavar="TABLE=SCOPE",
        help="source table to schema scope mapping, e.g. demo2=cell",
    )
    parser.add_argument(
        "--schema-output",
        required=True,
        metavar="PATH",
        help="output RM schema JSON file",
    )
    parser.add_argument(
        "--report-output",
        required=True,
        metavar="PATH",
        help="output conversion report JSON file",
    )
    parser.add_argument(
        "--word-width",
        type=int,
        default=DEFAULT_WORD_WIDTH,
        help="schema word width; default is 32",
    )
    return parser


def main(argv=None):
    parser = build_argument_parser()
    args = parser.parse_args(argv)
    try:
        scope_rules = _load_scope_rules(args.scope_rule)
        if args.input:
            roots = parse_uvm_table_tree(_read_text(args.input))
            document = {"format": "uvm_table_printer/v1", "roots": roots}
        else:
            document = _read_json(args.json_input)
        result = compile_schema_from_uvm_table_json(
            document,
            schema_id=args.schema_id,
            scope_rules=scope_rules,
            word_width=args.word_width,
        )
        _write_file(args.schema_output, render_json(result.schema_dict))
        _write_file(args.report_output, render_json(result.report))
    except UvmTableSchemaAdapterError as exc:
        print("error: {0}".format(exc), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
