"""Bind UVM table-printer values into an RM UserConfig dictionary."""

from __future__ import print_function

import argparse
import json
import os
import re
import sys
import tempfile
from collections import OrderedDict

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC_ROOT = os.path.join(REPO_ROOT, "src")
for _path in (REPO_ROOT, SRC_ROOT):
    if _path not in sys.path:
        sys.path.insert(0, _path)

from rm_ref.schema import SchemaDefinition
from utils.parse_uvm_table_print import parse_uvm_table_tree


GENERATED_HEADER = "Generated by utils/uvm_table_config_adapter.py"
DEFAULT_CASE_NAME = "uvm_table_config"


class UvmTableConfigAdapterError(Exception):
    """Raised when UVM table config binding cannot continue."""


class ConfigBindingResult(object):
    def __init__(self, config_dict, report):
        self.config_dict = config_dict
        self.report = report

    @property
    def has_errors(self):
        return bool(self.report.get("errors"))


class _FieldIndex(object):
    def __init__(self, schema):
        self.schema = schema
        self.by_full_key = {}
        self.by_scope_word_raw = {}
        self.by_raw_name = {}
        for field in schema.fields:
            raw_name = field.original_name
            full_key = (field.scope, field.word, field.msb, field.lsb, raw_name)
            self.by_full_key.setdefault(full_key, []).append(field)
            scope_word_key = (field.scope, field.word, raw_name)
            self.by_scope_word_raw.setdefault(scope_word_key, []).append(field)
            self.by_raw_name.setdefault(raw_name, []).append(field)

    def match(self, scope, raw_name, word, msb, lsb):
        if word is not None and msb is not None and lsb is not None:
            candidates = self.by_full_key.get((scope, word, msb, lsb, raw_name), [])
            if len(candidates) == 1:
                return candidates[0], "scope_word_bits_raw"
            if len(candidates) > 1:
                return list(candidates), "ambiguous_scope_word_bits_raw"

        if word is not None:
            candidates = self.by_scope_word_raw.get((scope, word, raw_name), [])
            if len(candidates) == 1:
                return candidates[0], "scope_word_raw"
            if len(candidates) > 1:
                return list(candidates), "ambiguous_scope_word_raw"

        candidates = self.by_raw_name.get(raw_name, [])
        if len(candidates) == 1:
            candidate = candidates[0]
            if candidate.scope == scope:
                return candidate, "unique_raw_name"
            return [], "unknown_scope_for_unique_raw_name"
        if len(candidates) > 1:
            return list(candidates), "ambiguous_raw_name"
        return [], "unknown"


def _ordered_dict():
    return OrderedDict()


def _as_schema(schema_or_dict):
    if isinstance(schema_or_dict, SchemaDefinition):
        return schema_or_dict
    if isinstance(schema_or_dict, dict):
        return SchemaDefinition.from_dict(schema_or_dict)
    raise TypeError("schema must be SchemaDefinition or dict")


def _as_roots(document_or_roots):
    if isinstance(document_or_roots, dict):
        if "roots" not in document_or_roots:
            raise UvmTableConfigAdapterError(
                "UVM table JSON document must contain roots"
            )
        return document_or_roots["roots"]
    return document_or_roots


def _parse_bit_range(field_type):
    match = re.search(r"\[(?P<msb>[0-9]+):(?P<lsb>[0-9]+)\]", field_type or "")
    if not match:
        return None
    msb = int(match.group("msb"), 10)
    lsb = int(match.group("lsb"), 10)
    if msb < lsb:
        return None
    return msb, lsb


def _is_word_marker(name):
    return re.match(r"^word[0-9]+$", name or "") is not None


def _word_index(name):
    return int(name[4:], 10)


def _is_payload_node(node):
    name = (node.get("name") or "").lower()
    field_type = (node.get("type") or "").lower()
    return name == "payload" or field_type.startswith("da(")


def _new_report(schema):
    report = _ordered_dict()
    report["schema_id"] = schema.schema_id
    report["input_field_count"] = 0
    report["bound_field_count"] = 0
    report["skipped_reserved_count"] = 0
    report["skipped_payload_count"] = 0
    report["unknown_field_count"] = 0
    report["ambiguous_field_count"] = 0
    report["type_error_count"] = 0
    report["range_error_count"] = 0
    report["unsupported_format_count"] = 0
    report["missing_context_count"] = 0
    report["warnings"] = []
    report["errors"] = []
    report["bound_fields"] = []
    report["skipped_fields"] = []
    return report


def _report_error(report, code, message, node=None, field=None):
    item = _ordered_dict()
    item["code"] = code
    item["message"] = message
    if node is not None:
        item["input_name"] = node.get("name")
        item["input_type"] = node.get("type")
        if "value" in node:
            item["input_value"] = node.get("value")
    if field is not None:
        item["field_name"] = field.normalized_name
        item["scope"] = field.scope
        item["word"] = field.word
        item["msb"] = field.msb
        item["lsb"] = field.lsb
    report["errors"].append(item)


def _report_warning(report, message, node=None):
    item = _ordered_dict()
    item["message"] = message
    if node is not None:
        item["input_name"] = node.get("name")
    report["warnings"].append(item)


def _scope_rules_from_schema(schema):
    metadata = getattr(schema, "metadata", {}) or {}
    rules = metadata.get("scope_rules", {})
    if isinstance(rules, dict):
        return dict(rules)
    return {}


def _scope_for_root(root, schema, scope_rules):
    root_name = root.get("name")
    rules = {}
    rules.update(_scope_rules_from_schema(schema))
    rules.update(scope_rules or {})
    scope = rules.get(root_name)
    if scope is None:
        field_scopes = set(field.scope for field in schema.fields)
        if len(field_scopes) == 1:
            scope = list(field_scopes)[0]
    if scope not in ("packet", "cell"):
        raise UvmTableConfigAdapterError(
            "no packet/cell scope rule for source table {0!r}".format(root_name)
        )
    return scope


def _document_has_context_indexes(root):
    if root.get("packet_index") is not None or root.get("cell_index") is not None:
        return True
    for child in root.get("children") or []:
        if _document_has_context_indexes(child):
            return True
    return False


def _initial_context(root, default_packet_index, default_cell_index):
    packet_index = root.get("packet_index")
    cell_index = root.get("cell_index")
    if packet_index is None:
        packet_index = default_packet_index
    if cell_index is None:
        cell_index = default_cell_index
    return packet_index, cell_index


def _context_for_node(node, packet_index, cell_index):
    next_packet = node.get("packet_index")
    next_cell = node.get("cell_index")
    if next_packet is None:
        next_packet = packet_index
    if next_cell is None:
        next_cell = cell_index
    return next_packet, next_cell


def _new_config(schema, case_name, algorithm_name):
    config = _ordered_dict()
    config["case_name"] = case_name
    config["algorithm_name"] = algorithm_name
    config["schema_id"] = schema.schema_id
    config["global_values"] = _ordered_dict()
    config["packets"] = []
    return config


def _packet_entry(config, packet_index):
    for packet in config["packets"]:
        if packet["packet_index"] == packet_index:
            return packet
    packet = _ordered_dict()
    packet["packet_index"] = packet_index
    packet["values"] = _ordered_dict()
    packet["cells"] = []
    config["packets"].append(packet)
    config["packets"].sort(key=lambda item: item["packet_index"])
    return packet


def _cell_entry(packet, cell_index):
    for cell in packet["cells"]:
        if cell["cell_index"] == cell_index:
            return cell
    cell = _ordered_dict()
    cell["cell_index"] = cell_index
    cell["values"] = _ordered_dict()
    packet["cells"].append(cell)
    packet["cells"].sort(key=lambda item: item["cell_index"])
    return cell


def _parse_value(value):
    if isinstance(value, bool):
        return None, "boolean values are not supported"
    if isinstance(value, int):
        return value, None
    if isinstance(value, str):
        stripped = value.strip()
        if re.match(r"^[0-9]+$", stripped):
            return int(stripped, 10), None
        if re.match(r"^0[xX][0-9a-fA-F_]+$", stripped):
            return int(stripped.replace("_", ""), 16), None
        if re.match(r"^0[bB][01_]+$", stripped):
            return int(stripped.replace("_", ""), 2), None
        return None, "unsupported value format {0!r}".format(value)
    return None, "value must be int or string, got {0!r}".format(value)


def _field_max_value(field):
    if field.width is None:
        return None
    return (1 << field.width) - 1


def _bind_value(config, packet_index, cell_index, field, value):
    if field.scope == "packet":
        packet = _packet_entry(config, packet_index)
        packet["values"][field.normalized_name] = value
    elif field.scope == "cell":
        packet = _packet_entry(config, packet_index)
        cell = _cell_entry(packet, cell_index)
        cell["values"][field.normalized_name] = value
    else:
        raise UvmTableConfigAdapterError(
            "unsupported field scope {0!r}".format(field.scope)
        )


def _record_bound(report, node, field, packet_index, cell_index, value, strategy):
    item = _ordered_dict()
    item["input_name"] = node.get("name")
    item["field_name"] = field.normalized_name
    item["scope"] = field.scope
    item["packet_index"] = packet_index
    item["cell_index"] = cell_index
    item["word"] = field.word
    item["msb"] = field.msb
    item["lsb"] = field.lsb
    item["value"] = value
    item["match_strategy"] = strategy
    report["bound_fields"].append(item)
    report["bound_field_count"] += 1


def _record_skipped(report, node, reason, field=None):
    item = _ordered_dict()
    item["input_name"] = node.get("name")
    item["reason"] = reason
    if field is not None:
        item["field_name"] = field.normalized_name
    report["skipped_fields"].append(item)


def _bind_leaf(
    config,
    report,
    field_index,
    scope,
    node,
    current_word,
    packet_index,
    cell_index,
):
    if _is_payload_node(node):
        report["skipped_payload_count"] += 1
        _record_skipped(report, node, "payload")
        return

    report["input_field_count"] += 1
    bit_range = _parse_bit_range(node.get("type"))
    msb = None
    lsb = None
    if bit_range is not None:
        msb, lsb = bit_range
    field_or_candidates, strategy = field_index.match(
        scope, node.get("name"), current_word, msb, lsb
    )
    if isinstance(field_or_candidates, list):
        if field_or_candidates:
            report["ambiguous_field_count"] += 1
            _report_error(
                report,
                "ambiguous_field",
                "input field {0!r} matched {1} schema fields by {2}".format(
                    node.get("name"), len(field_or_candidates), strategy
                ),
                node=node,
            )
        else:
            report["unknown_field_count"] += 1
            _report_error(
                report,
                "unknown_field",
                "schema has no field for input {0!r} at scope {1}, word {2}".format(
                    node.get("name"), scope, current_word
                ),
                node=node,
            )
        return

    field = field_or_candidates
    if field.reserved:
        report["skipped_reserved_count"] += 1
        _record_skipped(report, node, "reserved", field=field)
        return

    if "value" not in node:
        report["type_error_count"] += 1
        _report_error(
            report,
            "missing_value",
            "input field {0!r} has no value".format(node.get("name")),
            node=node,
            field=field,
        )
        return

    converted, error = _parse_value(node.get("value"))
    if error is not None:
        report["type_error_count"] += 1
        if error.startswith("unsupported value format"):
            report["unsupported_format_count"] += 1
            code = "unsupported_format"
        else:
            code = "type_error"
        _report_error(report, code, error, node=node, field=field)
        return

    max_value = _field_max_value(field)
    if converted < 0 or (max_value is not None and converted > max_value):
        report["type_error_count"] += 1
        report["range_error_count"] += 1
        _report_error(
            report,
            "range_error",
            "field {0} value {1!r} exceeds unsigned width {2}".format(
                field.normalized_name, converted, field.width
            ),
            node=node,
            field=field,
        )
        return

    if field.scope == "cell" and cell_index is None:
        report["missing_context_count"] += 1
        _report_error(
            report,
            "missing_required_context",
            "cell-scope field {0} has no cell_index".format(field.normalized_name),
            node=node,
            field=field,
        )
        return
    if packet_index is None:
        report["missing_context_count"] += 1
        _report_error(
            report,
            "missing_required_context",
            "field {0} has no packet_index".format(field.normalized_name),
            node=node,
            field=field,
        )
        return

    _bind_value(config, packet_index, cell_index, field, converted)
    _record_bound(report, node, field, packet_index, cell_index, converted, strategy)


def _walk_nodes(
    nodes,
    config,
    report,
    field_index,
    scope,
    state,
    packet_index,
    cell_index,
):
    current_word = state.get("current_word")
    for node in nodes:
        next_packet, next_cell = _context_for_node(node, packet_index, cell_index)
        children = node.get("children")
        if children is not None:
            child_state = {"current_word": current_word}
            _walk_nodes(
                children,
                config,
                report,
                field_index,
                scope,
                child_state,
                next_packet,
                next_cell,
            )
            current_word = child_state.get("current_word")
            state["current_word"] = current_word
            continue

        name = node.get("name")
        if _is_word_marker(name):
            current_word = _word_index(name)
            state["current_word"] = current_word
            continue

        _bind_leaf(
            config,
            report,
            field_index,
            scope,
            node,
            current_word,
            next_packet,
            next_cell,
        )


def _has_duplicate_unindexed_roots(roots):
    names = {}
    for root in roots:
        name = root.get("name")
        names[name] = names.get(name, 0) + 1
    for root in roots:
        if names.get(root.get("name"), 0) > 1 and not _document_has_context_indexes(root):
            return True
    return False


def bind_config_from_uvm_table_json(
    document_or_roots,
    schema,
    scope_rules=None,
    case_name=DEFAULT_CASE_NAME,
    algorithm_name="",
    default_packet_index=0,
    default_cell_index=0,
):
    schema = _as_schema(schema)
    roots = _as_roots(document_or_roots)
    if not isinstance(roots, list) or not roots:
        raise UvmTableConfigAdapterError("UVM table roots must be a non-empty list")

    config = _new_config(schema, case_name, algorithm_name)
    report = _new_report(schema)
    field_index = _FieldIndex(schema)

    if _has_duplicate_unindexed_roots(roots):
        report["missing_context_count"] += 1
        _report_error(
            report,
            "missing_required_context",
            "multiple source roots share a table name without packet_index/cell_index",
        )
        return ConfigBindingResult(config, report)

    for root in roots:
        scope = _scope_for_root(root, schema, scope_rules)
        packet_index, cell_index = _initial_context(
            root, default_packet_index, default_cell_index
        )
        children = root.get("children")
        if children is None:
            _report_warning(
                report,
                "source table {0!r} has no children".format(root.get("name")),
                node=root,
            )
            continue
        _walk_nodes(
            children,
            config,
            report,
            field_index,
            scope,
            {},
            packet_index,
            cell_index,
        )

    return ConfigBindingResult(config, report)


def render_json(data):
    return json.dumps(data, indent=2, ensure_ascii=True) + "\n"


def _read_text(path):
    if not os.path.isfile(path):
        raise UvmTableConfigAdapterError("input file not found: {0}".format(path))
    try:
        with open(path, "r", encoding="utf-8") as handle:
            return handle.read()
    except (IOError, OSError) as exc:
        raise UvmTableConfigAdapterError(
            "cannot read input file {0}: {1}".format(path, exc)
        )


def _read_json(path):
    if not os.path.isfile(path):
        raise UvmTableConfigAdapterError("JSON file not found: {0}".format(path))
    try:
        with open(path, "r", encoding="utf-8") as handle:
            return json.load(handle)
    except (IOError, OSError, ValueError) as exc:
        raise UvmTableConfigAdapterError(
            "cannot read JSON file {0}: {1}".format(path, exc)
        )


def _write_file(path, content):
    output_path = os.path.abspath(path)
    output_directory = os.path.dirname(output_path)
    if not os.path.isdir(output_directory):
        raise UvmTableConfigAdapterError(
            "output directory does not exist: {0}".format(output_directory)
        )
    temporary_path = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            newline="\n",
            dir=output_directory,
            prefix=".uvm_config_",
            suffix=".tmp",
            delete=False,
        ) as handle:
            temporary_path = handle.name
            handle.write(content)
        os.replace(temporary_path, output_path)
    except (IOError, OSError) as exc:
        if temporary_path is not None and os.path.exists(temporary_path):
            try:
                os.remove(temporary_path)
            except (IOError, OSError):
                pass
        raise UvmTableConfigAdapterError(
            "cannot write output file {0}: {1}".format(path, exc)
        )


def _parse_scope_rule(text):
    if "=" not in text:
        raise UvmTableConfigAdapterError(
            "scope rule must use TABLE=SCOPE syntax: {0!r}".format(text)
        )
    table, scope = text.split("=", 1)
    table = table.strip()
    scope = scope.strip()
    if not table or not scope:
        raise UvmTableConfigAdapterError(
            "scope rule must use TABLE=SCOPE syntax: {0!r}".format(text)
        )
    return table, scope


def _load_scope_rules(scope_rule_values):
    rules = OrderedDict()
    for value in scope_rule_values or []:
        table, scope = _parse_scope_rule(value)
        rules[table] = scope
    return rules


def build_argument_parser():
    parser = argparse.ArgumentParser(
        description=(
            "Bind UVM table-printer values into an RM UserConfig-compatible "
            "dictionary."
        )
    )
    input_group = parser.add_mutually_exclusive_group(required=True)
    input_group.add_argument(
        "--input",
        metavar="PATH",
        help="UVM table-printer text input; parsed with the existing parser",
    )
    input_group.add_argument(
        "--json-input",
        metavar="PATH",
        help="pre-rendered uvm_table_printer/v1 JSON input",
    )
    parser.add_argument(
        "--schema",
        required=True,
        metavar="PATH",
        help="RM schema JSON accepted by SchemaDefinition.from_dict()",
    )
    parser.add_argument(
        "--scope-rule",
        action="append",
        default=[],
        metavar="TABLE=SCOPE",
        help="source table to config scope mapping, e.g. demo2=cell",
    )
    parser.add_argument(
        "--case-name",
        default=DEFAULT_CASE_NAME,
        help="UserConfig case_name; default is uvm_table_config",
    )
    parser.add_argument(
        "--algorithm-name",
        default="",
        help="optional UserConfig algorithm_name",
    )
    parser.add_argument(
        "--default-packet-index",
        type=int,
        default=0,
        help="packet_index used when input has no explicit context; default 0",
    )
    parser.add_argument(
        "--default-cell-index",
        type=int,
        default=0,
        help="cell_index used when input has no explicit context; default 0",
    )
    parser.add_argument(
        "--config-output",
        required=True,
        metavar="PATH",
        help="output RM UserConfig-compatible JSON file",
    )
    parser.add_argument(
        "--report-output",
        required=True,
        metavar="PATH",
        help="output conversion report JSON file",
    )
    return parser


def main(argv=None):
    parser = build_argument_parser()
    args = parser.parse_args(argv)
    try:
        if args.input:
            roots = parse_uvm_table_tree(_read_text(args.input))
            document = {"format": "uvm_table_printer/v1", "roots": roots}
        else:
            document = _read_json(args.json_input)
        schema_dict = _read_json(args.schema)
        result = bind_config_from_uvm_table_json(
            document,
            schema_dict,
            scope_rules=_load_scope_rules(args.scope_rule),
            case_name=args.case_name,
            algorithm_name=args.algorithm_name,
            default_packet_index=args.default_packet_index,
            default_cell_index=args.default_cell_index,
        )
        _write_file(args.config_output, render_json(result.config_dict))
        _write_file(args.report_output, render_json(result.report))
    except UvmTableConfigAdapterError as exc:
        print("error: {0}".format(exc), file=sys.stderr)
        return 1
    return 1 if result.has_errors else 0


if __name__ == "__main__":
    sys.exit(main())
