# Auto-generated by utils/parse_uvm_table_print.py

def para_get(parse):
    parse.header0_packet_type = 0
    parse.header0_start_symbol = 0
    parse.header1_packet_type = 0
    parse.header1_start_symbol = 0
    parse.word4 = 0
